services:
  mongo_db:
    image: mongo
    container_name: orabuddy-mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_NAME
    ports:
      - '27017'
    volumes:
      - db:/data/db

volumes:
  db: